name: Build esp32 firmware

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./esp32

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - uses: actions/upload-artifact@v3
        with:
          name: esp32.elf
          path: .pio/build/esp32/firmware.elf
      
      - uses: actions/upload-artifact@v3
        with:
          name: esp32.bin
          path: .pio/build/esp32/firmware.bin